[package]
authors = ["Brian Smith <brian@briansmith.org>"]
build = "build.rs"
description = "A Rust interface for a simplification of BoringSSL's libcrypto."
license-file = "LICENSE"
name = "ring"
readme = "README.md"
repository = "https://github.com/briansmith/ring"
version = "0.1.0"

[lib]
name = "ring"

[dependencies]
lazy_static = "0.2.1"
untrusted = { git = "https://github.com/briansmith/untrusted" }

[build-dependencies.num]
version = "0.1.30"
default-features = false
features = ["bigint"]

[dev-dependencies]
rustc-serialize = "0.3.19"

[features]
# These features are documented in the top-level module's documentation.
disable_dev_urandom_fallback = []
no_heap = []
slow_tests = []
test_logging = []

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
