[package]
authors = ["Brian Smith <brian@briansmith.org>"]
build = "build.rs"
description = "A Rust interface for a simplification of BoringSSL's libcrypto."
license-file = "LICENSE"
name = "ring"
readme = "README.md"
repository = "https://github.com/briansmith/ring"
version = "0.1.0"

[lib]
name = "ring"

[dev-dependencies]
rustc-serialize = "0.3.15"
time = "0.1.32"

# Fix the `bench`, `release`, and `test` profiles so they all have the
# same configuration.
#
# XXX: We can't build with `debug = true` yet because that breaks the
# Windows builds. See https://github.com/briansmith/ring/issues/44.

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
